# Definindo o nome do Workflow
name: Teste Workflow

# Definindo quando o Workflow será disparado
on:
  push:
    branches: [ main, developer ]

# Definindo os jobs que o workflow executará
jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: 'marioguilhermedev'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          tags: 'latest'
          push: true
          
